### ISSUE TITLE
Better handling of warnings

### ISSUE THREAD

**Issue by mrtve** [tuunit/mkdocs-drawio#13]
The plugin throws a warning using a standard print output:
https://github.com/tuunit/mkdocs-drawio/blob/58c02d7d03770a78e84efa9dfe01b1b729bd3966/mkdocs_drawio/plugin.py#L99

It would be much better if the plugin either threw an error or warning using the MkDocs logging system.
It could be verbose saying that it expected a page number if there were multiple pages, following that it shows the name of the drawio file. Perhaps even the markdown page in which the problem occurred.

**Comment by tuunit** [comment]
Good catch. Do you want to implement the fix in a PR of your own?

**Comment by mrtve** [comment]
I have other problems to deal with in our MkDocs setup that are a bit more urgent, so this is not a high priority for me to fix..
But I like the plugin so the least I can do is to pass the feedback along :) Sorry I can't be of more help

**Comment by tuunit** [comment]
Fixed and release https://pypi.org/project/mkdocs-drawio/1.6.5/
