### ISSUE TITLE
Bump lxml to ^5.0.0

### ISSUE THREAD

**Issue by Antyos** [tuunit/mkdocs-drawio#4]
## Issue

Currently, this library cannot be added to projects which use lxml >= 5.0.0.

```bash
$ poetry add mkdocs-drawio -G docs     
Using version ^1.6.0 for mkdocs-drawio

Updating dependencies
Resolving dependencies... (0.0s)

Because no versions of mkdocs-drawio match >1.6.0,<2.0.0
 and mkdocs-drawio (1.6.0) depends on lxml (>=4.9.0,<5.0.0), mkdocs-drawio (>=1.6.0,<2.0.0) requires lxml (>=4.9.0,<5.0.0).
So, because my-project depends on both lxml (^5.1.0) and mkdocs-drawio (^1.6.0), version solving failed.
```

## Solution

I suspect this is due to the packaging constraints in the `pyproject.toml`:
https://github.com/tuunit/mkdocs-drawio/blob/ac4f5baadaa85e43b4476f78909db05532431075/pyproject.toml#L25.

From what I can tell, there is no need to limit the library to lxml 4.9, other than that was what was used at the time of the library's creation, so allowing anything above 4.9 should be fine. I would make a PR, but I am slightly confused as to how Poetry is being used in this repo; Poetry is not included in the dev container or the GitHub Actions workflow, so I don't know where/how the lxml version constraint was introduced.

If you are using Poetry for versioning, you should be able to replace the line noted above with:
```toml
lxml = ">=4.9.0"
```

**Comment by tuunit** [comment]
Thanks for opening the issue.
Release 1.6.1 is now available with all dependencies upgraded.

Please try again.

**Comment by tuunit** [comment]
Maybe I make another release to be less restrictive with the versions instead of forcing the latest newer version for all dependencies

**Comment by Antyos** [comment]
It works! Thank you so much!



> Maybe I make another release to be less restrictive with the versions instead of forcing the latest newer version for all dependencies

I am in favor of this. Take a look at: https://python-poetry.org/docs/dependency-specification/ for how to specify less restrictive versions.

**Comment by tuunit** [comment]
https://github.com/tuunit/mkdocs-drawio/releases
