### ISSUE TITLE
Invalid escape sequence

### ISSUE THREAD

**Issue by mvtab** [tuunit/mkdocs-drawio#7]
Hello,

I am using python 3.12 and mkdocs-material 9.5.28 with mkdocs-drawio 1.6.2 and have a weird effect.
On my development machine all goes well, I can serve and build with no problem. When I move the same setup to a python3.12-alpine, I receive the following error whenever I run mkdocs (serve or build):

```
12 9.648 INFO    -  SyntaxWarning: invalid escape sequence '\&'
#12 9.648   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
#12 9.648     return _bootstrap._gcd_import(name[level:], package, level)
#12 9.648   File "/opt/poetry/venv/ltb-infradoc-vnuQW1G_-py3.12/lib/python3.12/site-packages/mkdocs_drawio/plugin.py", line 110, in 
#12 9.648     str_xml = str_xml.replace('"', "\&quot;")
#12 9.648
```
However, even with the error the build continues and the website seems to be working fine. All diagrams are correctly displayed.

Any idea what can cause this? From what I know \\& is completely legit in python, or am I wrong?

**Comment by tuunit** [comment]
Hi @mvtab,

interesting this is due to a change in python 3.12:

https://docs.python.org/dev/whatsnew/3.12.html#other-language-changes

As it is just a warning it might not be displayed on your local environment because of the log level you have setup.

**Comment by tuunit** [comment]
I'll just have to update the code to use raw strings:

`str_xml = str_xml.replace('"', r"\&quot;")`

**Comment by tuunit** [comment]
Hi @mvtab,

I published v1.6.3 please check if it still occurs.

**Comment by tuunit** [comment]
@mvtab were you able to check if the warning is gone? I'm not able to reproduce it anymore.

**Comment by mvtab** [comment]
Hi @tuunit,

the error doesn't appear anymore, thank you!

**Comment by tuunit** [comment]
Great now I can look at your other issue 😂
