### ISSUE TITLE
JSON.parse

### ISSUE THREAD

**Issue by mvtab** [tuunit/mkdocs-drawio#9]
Hi,

I am noticing a weird effect in a docker setup. I am using mkdocs-material 9.5.28, and on my dev machine all works fine, I can see all diagrams with mkdocs serve, but as soon as I build the website on a container and run it, all diagrams return this error instead of being displayed:

`JSON.parse: bad character in string literal at line 1 column 328 of the JSON data`
column 328 is different at some others, +- 30

I tried versions 1.5.2, 1.5.3, 1.5.4, 1.5.5 and there all was working still (even in the docker setup). 1.5.6-1.5.9 don't exist (at least anymore), and starting 1.6.0 I can see this effect.

EDIT: 
Maybe I'm missing some dependencies?
I currently have this installed on the container:

```
python = "^3.12"
aiofiles = "~24.1.0"
asyncio = "~3.4.3"
python-dotenv = "~1.0.1"
httpx = "~0.27.0"
mkdocs-material = "~9.5.28"
mkdocs-glightbox = "~0.4.0"
mkdocs-drawio = "~1.6.3"
mkdocs-minify-plugin = "~0.8.0"
mkdocs-redirects = "~1.2.1"
orjson = "~3.10.6"
pymdown-extensions = "~10.8.1"
```

Kind regards,
Alex

**Comment by tuunit** [comment]
Hi @mvtab,

which base image do you use?

**Comment by tuunit** [comment]
There never has been a version higher than 1.5.5. The next higher version is 1.6.0

I follow semver.org standards. Backwards compatible feature upgrade mean a minor version upgrade. The last digit is just the patch version for bug fixing.

**Comment by tuunit** [comment]
I was able to reproduce the issue and already have the fixed merged. The automated release should be out in a couple of seconds.

**Comment by mvtab** [comment]
Hehe so it was actually related to the previous issue. I wasn't sure, that's why I opened a new one.

I tested it now, it is working perfectly! Great job, thank you!

**Comment by mvtab** [comment]
P.S. Do you have any idea why were we seeing those effects only on containers?

**Comment by tuunit** [comment]
To be honest I have no idea how it was possible to be any different between the two
